[project]
name = "buildstate-cms"

[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
numReplicas = 1
restartPolicyType = "ON_FAILURE"

[env]
PYTHONUNBUFFERED = "1"
DJANGO_SETTINGS_MODULE = "cmspro.settings"
DEBUG = "False"
ALLOWED_HOSTS = "localhost,127.0.0.1,3hc-django-production-5f7a.up.railway.app"